twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - bootstrap_4_layout.html.twig

    globals:
        prenomdegary : gary
        CategoryRepository : "@App\\Repository\\CategoryRepository"
        cartService: "@App\\Cart\\CartService"
        app_environement: '%env(APP_ENV)%'
